expence_shairing_app/config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :expense_payments

  resources :dashboard_chart do
    collection do
      get 'plot'
      get 'expense_balance'
      get 'expense_table'
      get 'table_plot'
    end
  end
  resources :paid_users
	devise_for :users
	devise_scope :user do
		authenticated :user do
			root 'expense_payments#index', as: :authenticated_root
		end

		unauthenticated do
			root 'devise/sessions#new', as: :unauthenticated_root
		end
	end
  get 'home/index'
  devise_for :views
end



  

expence_shairing_app/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

expence_shairing_app/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

expence_shairing_app/app/models/expense.rb
class Expense < ApplicationRecord
end

expence_shairing_app/app/models/expense_payment.rb
class ExpensePayment < ApplicationRecord
	belongs_to :expense
	belongs_to :group
	has_many :paid_users
	delegate :name, to: :expense, allow_nil: true
end

expence_shairing_app/app/models/group.rb
class Group < ApplicationRecord
	belongs_to :owner, class_name: "User"
	has_many :group_users
  has_many :users, through: :group_users
	accepts_nested_attributes_for :users
end



	

expence_shairing_app/app/models/group_user.rb
class GroupUser < ApplicationRecord
	belongs_to :group
  belongs_to :user
end

expence_shairing_app/app/models/paid_user.rb
class PaidUser < ApplicationRecord
	belongs_to :expense_payment
	belongs_to :user
	validates :expense_payment_id, uniqueness: { scope: :user_id }
	delegate :first_name, to: :user, allow_nil: true
	delegate :date, to: :expense_payment, allow_nil: true
end

expence_shairing_app/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 	has_many :group_users 
 	has_many :groups, through: :group_users
end

expence_shairing_app/app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

expence_shairing_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

expence_shairing_app/app/controllers/dashboard_chart_controller.rb
class DashboardChartController < ApplicationController
	
	def index	
	end

	def plot
		data_set = ExpensePayment.where(:date => params['start_date'].to_date.beginning_of_day..params['end_date'].to_date.end_of_day).pluck(:expense_id,:amount).group_by(&:first)
		data_set = format_expense_data_set(data_set)
		render json: {data: data_set}
	end

	def format_expense_data_set(data_set)
		new_data={}
		data_set.each do |k, v|
			new_data[k]=v.map{|x| x[1]}.sum
		end
		new_data = new_data.to_a
		new_data.map{|x| x[0] = Expense.where(id: x[0])&.last&.name}
		new_data.map{|x| x[1]=x[1].to_f}
		new_data
	end

	def expense_balance
		expense_payment = ExpensePayment.find params['expense']
		@total_expense = expense_payment.amount
		@paid_users = expense_payment.paid_users
		@non_paid_users = User.where(id: expense_payment.group.users.pluck(:id)-@paid_users.pluck(:user_id))
		@share_amount = (@total_expense / expense_payment.group.users.count)
	end

	def expense_table
		if (params['group_id'] ||  params['user_id'])
      search_expense
		else
			expenses = ExpensePayment.includes(:expense,:group).includes(:expense).all
			group_expenses_share(expenses)
		end
	end

	def search_expense
		@payments=[]
		if params['group_id'].present?
   	  expenses = ExpensePayment.includes(:expense,:group).where(group_id: params['group_id'])
   	  group_expenses_share(expenses)
   	elsif params['user_id'].present?
   		expenses = PaidUser.where(user_id:  params['user_id'])
   		personal_expenses_share(expenses)
   	end
  end

  def group_expenses_share(expenses)
  	@payments=[]
  	expenses.each do |exp|
  		users = if params['user_id'].present?
  							exp.paid_users.where(user_id: params['user_id'])
  						else
  							exp.paid_users
  						end
		 	users.each do |exp_user|
	   		payment = [exp_user.expense_payment.name, exp_user.first_name, exp_user.expense_payment.group.name, exp_user.share_amount, exp_user.date]
	 	  	@payments << payment
	 	  end
	 	 end
  end

  def personal_expenses_share(expenses)
  	@payments=[]
	 	expenses.each do |exp_user|
   		payment = [exp_user.expense_payment.name, exp_user.first_name, exp_user.expense_payment.group.name, exp_user.share_amount, exp_user.date]
 	  	@payments << payment
 	  end
  end

end

expence_shairing_app/app/controllers/expense_payments_controller.rb
class ExpensePaymentsController < ApplicationController
	
	def new
    @expense_payment = ExpensePayment.new
  end

	def index
		@expense_payments = ExpensePayment.all
		@expense_payment = ExpensePayment.new
  end

  def create
    @expense_payment = ExpensePayment.new(expense_payment_params)
    if @expense_payment.save
      redirect_to expense_payments_path, notice: 'Expense added successfully'
    else
      redirect_to :back
    end
  end

  def show
    @expense_payment = ExpensePayment.where(id: params[:id]).last
    @share_holders = @expense_payment.group.users
    @paid_users = @expense_payment.paid_users.includes(:user).order('id desc')
    @paid_user = PaidUser.new
  end

  def expense_payment_params
    params.require(:expense_payment).permit(:amount, :expense_id, :group_id, :description)
  end
end

expence_shairing_app/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

expence_shairing_app/app/controllers/paid_users_controller.rb
class PaidUsersController < ApplicationController

  def create
    paid_user = PaidUser.new(paid_users_params)
    total_amount = expense_payment.amount
    if total_amount >= (payable_amount + paid_users_params['share_amount'].to_i)
      if paid_user.save
    	  redirect_to expense_payment_path(paid_user.expense_payment_id), notice: 'Successfully added your share.'
  	  else
        redirect_to expense_payment_path(paid_user.expense_payment_id), notice: 'Alredy added your share.'
      end
    else
      flash[:notice] = "Expense is lesser than paid amount."
      redirect_to expense_payment_path(paid_user.expense_payment_id)
  	end
  end

  def payable_amount
    paid_amount = expense_payment.paid_users&.pluck(:share_amount).sum
  end

  def expense_payment
    ExpensePayment.find(paid_users_params['expense_payment_id'])
  end

  def paid_users_params
    params.require(:paid_user).permit(:share_amount, :expense_payment_id, :user_id)
  end
end

expence_shairing_app/app/helpers/application_helper.rb
module ApplicationHelper
	
	def with_precision(number)
    number_to_currency(number)
  end

  def format_date(date)
    if date.present?
      date.to_date.strftime('%d/%m/%Y')
    else
      '--'
    end
  end
end

expence_shairing_app/app/helpers/dashboard_chart_helper.rb
module DashboardChartHelper
end

expence_shairing_app/app/helpers/expense_payments_helper.rb
module ExpensePaymentsHelper
end

expence_shairing_app/app/helpers/home_helper.rb
module HomeHelper
end

expence_shairing_app/app/views/dashboard_chart/_expense_chart.html.erb
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>
<body>
    <div class="col-md-2">
        <h3 class="ticket-margin">
          <i class="icon-calendar"></i><%= t('From') %></h3>
        <%= date_field :start_date, params[:start_date], value: Time.now.beginning_of_month.strftime('%Y-%m-%d'), name: 'daterange', id: "start_date",class: "form-control form-control-inline input-small date-picker date_range filter_date",size: "16" %>
    </div>
    <div class="col-md-2 pdng-egt-nne">
        <h3 class="ticket-margin">
          <i class="icon-calendar"></i><%= t('To') %></h3>
        <%= date_field :end_date, params[:end_date], value: Time.now.strftime('%Y-%m-%d'), name: 'daterange', id: "end_date" ,class: "form-control form-control-inline input-small date-picker date_range filter_date",size: "16" %>
    </div>
    <br/><br/>
    <div class="col2">
        <button id="sample_editable_1_new" class="btn sbold green btn-mrg" data-target="#stack1" data-toggle="modal"> <%= 'Plot Chart' %>
          <i class="fa fa-plus"></i>
        </button>
    </div> 
    <div id="pie_chart_container" style="height: 400px; min-width: 310px"></div>
</body>

expence_shairing_app/app/views/dashboard_chart/expense_balance.html.erb
<div class="feed-activity-list">
  <div class="feed-element">
	<div class="col-lg-4 col-sm-4 col-xs-12">
		<strong><%= 'Total Expense:'%></strong>
		<strong><%= with_precision(@total_expense)%></strong>
	</div>
    <%@paid_users.each_with_index do |paid_user, index| %>
      <div class='row'>

        <div class="col-lg-12 col-sm-12">
          <small class="pull-right"></small>
          <a href="#">
            <img alt="image" class="img-circle" src="/user_default.png">
          </a>
          <strong><%=paid_user.try(:first_name)%></strong>
          <div>
            <small class="text-muted">
              <%= I18n.l(paid_user.created_at, format: :long)%>
            </small>
          </div>
        </div>
        <div class="col-lg-12 col-sm-12">
          <div class='row' >
            <div class="col-lg-4 col-sm-4 col-xs-12">
              <%= 'Paid Amount:'%>
              <%= with_precision(paid_user.share_amount)%>
            </div>
          </div>
        </div>
        <div class="col-lg-12 col-sm-12">
          <div class='row' >
            <div class="col-lg-4 col-sm-4 col-xs-12">
            	<%= paid_user.user.try(:first_name) %> 
            	<%if (@share_amount < paid_user.share_amount)%>
            		<%= 'Paid Extra:'%>
              <%else%>
              	<%= 'Owes:'%>
              <%end%>
              	<%= with_precision((@share_amount-paid_user.share_amount).abs)%>
            </div>
          </div>
        </div>
        <div class="col-lg-12 col-sm-12 col-xs-12">
        </div>
      </div>
      <div class="clear"><br><br><br></div>
    <%end%>
    <%@non_paid_users.each_with_index do |non_paid_user, index| %>
         <div class='row'>
        <div class="col-lg-12 col-sm-12">
          <small class="pull-right"></small>
          <a href="#">
            <img alt="image" class="img-circle" src="/user_default.png">
          </a>
          <strong><%=non_paid_user.try(:first_name)%></strong>
          <div>
            <small class="text-muted">
              <%= I18n.l(non_paid_user.created_at, format: :long)%>
            </small>
          </div>
        </div>
        <div class="col-lg-12 col-sm-12">
          <div class='row' >
            <div class="col-lg-4 col-sm-4 col-xs-12">
              <%= 'Paid Amount:'%>
              <%= with_precision(0)%>
            </div>
          </div>
        </div>
        <div class="col-lg-12 col-sm-12">
          <div class='row' >
            <div class="col-lg-4 col-sm-4 col-xs-12">
              <%= non_paid_user.try(:first_name) %>            
                <%= 'Owes:'%>
                <%= with_precision((@share_amount).abs)%>
            </div>
          </div>
        </div>
        <div class="col-lg-12 col-sm-12 col-xs-12">
        </div>
      </div>
      <div class="clear"><br><br><br></div>
    <%end%>
    <div class="clear"><br></div>
    <div class="clear"><br></div>
  </div>
</div>

expence_shairing_app/app/views/dashboard_chart/expense_table.html.erb
<%= form_tag(expense_table_dashboard_chart_index_path, method: :get) do %>
  <strong> Search for expense </strong>
  <%= select_tag "group_id", options_from_collection_for_select(Group.all, "id", "name"),:class => 'form-control', prompt: 'please select group' , selected: params[:group_id] %></br></br>
  <%= select_tag "user_id", options_from_collection_for_select(User.all, "id", "first_name"),:class => 'form-control', prompt: 'please select payee' %></br></br>
  <%= submit_tag ("Search") %>
<% end %>
<h1>Payments</h1>
<table>
  <tr>
    <th>Expense</th>
    <th>Payee</th>
    <th>Group</th>
    <th>Amount</th>
    <th>Paid At</th>
  </tr>
  <% @payments.each do |payment| %>
    <tr>
      <td><%= payment[0]%></td>
      <td><%= payment[1] %></td>
      <td><%= payment[2] %></td>
      <td><%= with_precision(payment[3])%></td>
      <td><%= format_date(payment[4])%></td>
    </tr>
  <% end %>
  </table>

expence_shairing_app/app/views/dashboard_chart/index.html.erb
<%= javascript_pack_tag "expense_share.js" %>
<div>
<%= render 'expense_chart' %>
</div>

expence_shairing_app/app/views/expense_payments/_new.html.erb
<div class="wrapper wrapper-content">
  <div class = "clear"></div>
  <div class="wrapper-content margin_top">
    <%= form_for(@expense_payment) do |f| %>
      <div class="row">
        <div class="col-lg-4">
          <%= f.label 'Expense' %>
        </div>
        <div class="col-lg-4">
          <%= f.select(:expense_id, options_for_select(Expense.all.collect{ |u| [u.name, u.id] }), {include_blank: 'Select Expense'}, { :class => 'chosen-input' }) %>
       </div>
      </div>
      <div class="clear"><br></div>
      <div class="row">
        <div class="col-lg-4">
          <%= f.label 'Group' %>
        </div>
        <div class="col-lg-4">
          <%= f.select(:group_id, options_for_select(Group.all.collect{ |u| [u.name, u.id] }), {include_blank: 'Select Group'}, { :class => 'chosen-input' }) %>
        </div>
      </div>
      <div class="clear"><br></div>
      <div class="row">
        <div class="col-lg-4">
          <%= f.label 'Amount' %>
        </div>
        <div class="col-lg-4">
          <%= f.number_field :amount, required: true, style: "width: 110%;" %>
        </div>
      </div>
      <div class="clear"><br></div>
      <div class="row">
        <div class="col-lg-4">
          <%= f.label 'Date' %>
        </div>
        <div class="col-lg-4">
          <%= f.date_field :date, required: true, value: Time.now.strftime('%Y-%m-%d'),style: "width: 110%;" %>
        </div>
      </div>
      <div class="clear"><br></div>
      <div class="row">
        <div class="col-lg-4">
          <%= f.label 'Description' %>
        </div>
        <div class="col-lg-4">
          <%= f.text_field :description, required: true, style: "width: 110%;" %>
        </div>
      </div>
      <div class="clear"><br></div>
      <div class="row">
        <div class="col-lg-4">
        </div>
        <div class="col-lg-4">
           <%= f.submit 'Add Expense', class: "btn btn-large btn-primary" %>
        </div>
        <div class="col-lg-4">
        </div>
        <div class="col-lg-4">
          <%= link_to 'Chart', dashboard_chart_index_path, method: :get, class: "btn btn-xs btn-primary" %>
          <%= link_to 'Spending Summary', expense_table_dashboard_chart_index_path, method: :get, class: "btn btn-xs btn-primary" %>
        </div>
      </div>
    <% end %>
 </div>
</div>

expence_shairing_app/app/views/expense_payments/_new_payees.html.erb
 <%= form_for (@paid_user) do |f| %>
    <div class="wrapper wrapper-content">
      <div class="ibox">
        <div class="ibox-content">
          <div class="row">
            <div class="col-lg-4  col-sm-4">
              <%='Payee'%>
            </div>
            <div class="col-lg-8 col-sm-8">
            	<%= f.select(:user_id, options_for_select(@share_holders.collect{ |u| [u.first_name, u.id] }), {include_blank: 'Select Payee'}, { :class => 'chosen-input' }) %>
            </div>
          </div>
          <br/>
          <div class="row">
            <div class="col-lg-4 col-sm-4">
              <%='Amount'%>
            </div>
            <div class="col-lg-8 col-sm-8">
              <%= f.text_field :share_amount, class: 'negotiation_text_field'%>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-10 col-sm-10">
            </div>
            <div class="col-lg-2 col-sm-2">
              <%= f.hidden_field :expense_payment_id, value: @expense_payment.id %>
              <%= f.submit 'Add Payee' ,id: "add_payee_btn", class: "btn btn-xs btn-primary"%>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

expence_shairing_app/app/views/expense_payments/_payees.html.erb
<div class="feed-activity-list">
  <div class="feed-element">
    <%@expense_payment.paid_users.each_with_index do |paid_user, index| %>
      <div class='row'>
        <div class="col-lg-12 col-sm-12">
          <small class="pull-right"></small>
          <a href="#">
            <img alt="image" class="img-circle" src="/user_default.png">
          </a>
          <strong><%=paid_user.user.try(:first_name)%></strong>
          <div>
            <small class="text-muted">
              <%= I18n.l(paid_user.created_at, format: :long)%>
            </small>
          </div>
        </div>
        <div class="col-lg-12 col-sm-12">
          <div class='row' >
            <div class="col-lg-4 col-sm-4 col-xs-12">
              <%= 'Paid Amount:'%>
              <%= with_precision(paid_user.share_amount)%>
            </div>
          </div>
        </div>
        <div class="col-lg-12 col-sm-12 col-xs-12">
        </div>
      </div>
      <div class="clear"><br><br><br></div>
    <%end%>
    <div class="clear"><br></div>
    <div class="clear"><br></div>
    <div>
      <%= render 'new_payees' %>
    </div>
  </div>
</div>

expence_shairing_app/app/views/expense_payments/index.html.erb
<div style="clear: both;"></br></br></br></div>
  <%= render "new", locals: {expense_payment: @expense_payment} %>
  <%if @expense_payments.present? %>
    <div class="generic">
      <div class="ibox-title">
        <h3>Payment Histories</h3>
        <div class="ibox-tools col-lg-3 pull-right">
          <div class="input-group">
            <span class="input-group-btn">
            </span>
          </div>
        </div>
        <div style="clear: both;"></div>
      </div>
      <div class="ibox-content">
        <div class="table-responsive">
          <table class="table table-hover no-margins">
          <thead>
            <tr>
              <th>#</th>
              <th>Expense</th>
              <th>Group</th>
              <th>Amount</th>
              <th></th>
              <th></th>
              </tr>
            </thead>
          <tbody>
            <%@count = 1%>
            <%@expense_payments.each_with_index do |payment, index| %>
            <tr>
            <td><%= @count+ index %></td>
            <td><%=payment&.expense&.name%></td>
            <td><%=payment&.group&.name%></td>
            <td><%=with_precision(payment&.amount)%></td>
            <td><%= link_to 'Add Payee', expense_payment_path(payment), method: :get, class: "btn btn-xs btn-primary" %></td>
             <td><%= link_to 'Balance', expense_balance_dashboard_chart_index_path(expense: payment), method: :get, class: "btn btn-xs btn-primary" %></td>
              </tr>
          <% end %>
          </tbody>
        </table>
        </div>
      </div>
    </div>
  <%end%>
</div>

expence_shairing_app/app/views/expense_payments/show.html.erb
<a href="<%=dashboard_chart_index_path%>" ><%='Chart'%></a>
</li> 
<div class="row">
  <div class="col-lg-9">
    <div class="wrapper wrapper-content animated fadeInUp">
      <div class="ibox">
        <div class="ibox-content">
          <div class="row">
            <div class="col-lg-12">
              <div class="m-b-md">
                <h3><%='Expense'%><%=': '%><%= @expense_payment.expense.name%></h3>
              </div>
              <div class="m-b-md">
                <h3><%='Group'%><%=': '%><%= @expense_payment.group.name%></h3>
              </div>
              <div class="m-b-md">
                <h3><%='Amount'%><%=': '%><%= with_precision(@expense_payment.amount)%></h3>
              </div>
            </div>
          </div>
          <div class="row m-t-sm">
            <div class="col-lg-12">
              <div class="panel blank-panel">
                <div class="ibox-content">
                   <div class="clear"><br><br></div>
                </div>
                <div class="panel-body">
                  <%= render 'payees' %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

expence_shairing_app/app/views/home/index.html.erb
<% name = current_user.present? ? current_user.email : 'Stranger' %>

<h1>Welcome To Expence Shairing App, <%= name %> </h1>
<p>Find me in app/views/home/index.html.erb</p>

expence_shairing_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

expence_shairing_app/app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Add Your Expenses</a>
   <img alt="image" class="img-circle" src="/expense.png">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'nav-link' %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Sign In', new_user_session_path, class: 'nav-link' %>
            </li>
            <li class="nav-item">
                <%= link_to 'Register', new_user_registration_path, class: 'nav-link' %>
            </li>
        <% end %>
    </ul>
  </div>
</nav>